In [12]:
import pandas as pd
import numpy as np

dataset=pd.read_csv('cardio_dataset.csv').values

data=dataset[:,0:7]
target=dataset[:,7]

target=np.reshape(target, (-1,1))

print(data[:10])
print(target[:10])
print('size of the dataset:',len(dataset))

[[  2.  48. 236.  66.   0.   2.   0.]
 [  1.  48. 260.  51.   0.   2.   1.]
 [  1.  44. 187.  49.   1.   2.   0.]
 [  2.  42. 216.  57.   1.   2.   0.]
 [  2.  56. 156.  42.   0.   2.   0.]
 [  1.  44. 162.  57.   1.   2.   0.]
 [  1.  50. 244.  47.   0.   2.   0.]
 [  1.  48. 212.  30.   1.   2.   0.]
 [  2.  66. 202.  53.   0.   2.   1.]
 [  1.  63. 186.  46.   1.   2.   0.]]
[[ 1.1]
 [ 7. ]
 [ 7. ]
 [ 0.4]
 [ 2.2]
 [ 3. ]
 [ 4.2]
 [17.4]
 [13.4]
 [17.3]]
size of the dataset: 6644


In [4]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [7]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(train_data,train_target)
predicted_target=model.predict(test_data)

In [9]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print("r2 score:",r2)

r2 score: 0.7682818316457435


In [13]:
print('Actual Target:',test_target[:10].T)
print('Predicted Target:',predicted_target[:10].T)

Actual Target: [[ 1.4 22.   0.5  0.9  3.6  9.9 28.5  4.4 40.7  7.8]]
Predicted Target: [[-5.40621834 24.87065982 -6.93699136 -1.6126808   9.05504758 16.53599197
  34.78384281  9.17767641 32.05657156 15.3467359 ]]
